server:
    port: 7022

spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    data:
        mongodb:
            uri: mongodb://aruix:xingyudong@aruix.world/
            authentication-database: admin
            database: xjtlu-book